version: "3"

services:
  dnscrypt-proxy:
    container_name: dnscrypt-proxy
    image: ghcr.io/shmick/docker-dnscrypt-proxy
    ports:
      - "5300:5300/tcp"
      - "5300:5300/udp"
    restart: unless-stopped
