version: "3"

services:
  dnscrypt-proxy:
    container_name: dnscrypt-proxy
    image: shmick/dnscrypt-proxy:latest
    ports:
      - "5300:5300/tcp"
      - "5300:5300/udp"
    restart: unless-stopped
