name: Create and publish a Docker image

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Set env
        run: echo "APPVER=$(grep "ENV VERSION" Dockerfile | awk -F\" '{print $2}')" >> $GITHUB_ENV
      -
        name: Test
        run: echo $APPVER
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # -
      #   name: Login to DockerHub
      #   uses: docker/login-action@v1 
      #   with:
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.DOCKERHUB_PASS }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/arm/v7,linux/arm64,linux/amd64
          #platforms: linux/arm/v7,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest,ghcr.io/${{ github.repository }}:${{ env.APPVER }}
